site_url: https://docs.amis.work/
site_name: SQLAlchemy-Database
site_description: SQLAlchemy-Database provides shortcut functions to common database operations for SQLAlchemy ORM.
repo_url: https://github.com/amisadmin/sqlalchemy_database
edit_uri: edit/master/docs/
theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: true
            show_source: false

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://hm.baidu.com/hm.js?0b1b8a60b3a22ae45d1f04245f409fe2
  - js/chat.js
  - js/sidecar-1.5.0.js

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 简体中文
      link: /
      lang: zh

nav:
  - Tutorials:
      - README.md

  - API References:
      - Reference/Database.md
      - Reference/AsyncDatabase.md
      - Reference/AbcAsyncDatabase.md

